version: "3"

services:
  memcached:
    image: memcached:1.6-alpine

  redis:
    image: redis:6-alpine

  web:
    build:
      context: ../.
      dockerfile: ./docker/web/Dockerfile
    command: ./docker/web/start.sh
    env_file:
      - ./envs/development/.django
    volumes:
      - ./..:/code
    ports:
      - "8000:8000"
    depends_on:
      - memcached
      - redis
